mp.messaging.incoming.lra-request.connector=smallrye-kafka
mp.messaging.incoming.lra-request.enabled=${quarkus.lra.kafka.enabled:false}
mp.messaging.incoming.lra-request.topic=${quarkus.lra.coordinator-topic:lra-request}
mp.messaging.incoming.lra-request.auto.offset.reset=earliest

quarkus.lra.listener.protocol=${:http}
